### ISSUE TITLE
No one can use it easily except yourself, hahaha!!!Deploy it to docker!

### ISSUE THREAD

**Issue by LRF520** [danielpine/dmonitor#2]
The experience is very, very poor, very unfriendly, and it can't run at all! I suspect that you have seriously missed a large number of configuration file descriptions and auxiliary software descriptions. You even use a large number of fixed parameters. You are the only person in the world who can use this tool! No one can use it easily except yourself, hahaha!!!Deploy it to docker!

![20220729_011917](https://user-images.githubusercontent.com/58470642/181599659-1a1a57b9-7a6b-45ac-b230-1fe7cb87c067.jpg)

**Comment by danielpine** [comment]
its seens like you have no an es server,
and i used an old ElasticSearch client,you intalled a newly es client,some es pameters is not compatibility，i will fix it. 
i storage the metric data into sqlitedb or es by config,
if you have no es,
you can change the config/application.yml dmonitor.store to DB.  hhh
this project is startup and used to resolve some non-functional tests of my last job,
its may not taste so good,but we can make it better together.

**Comment by LRF520** [comment]
> 看来你没有es服务器， 我用的是旧的ElasticSearch客户端，你安装了一个新的es客户端，有些es参数不兼容，我会修复它。 我通过config将metric数据存入sqlitedb或es， 如果没有es， 可以将config/application.yml dmonitor.store改成DB。hhh 这个项目是启动的，用来解决我上一份工作的一些非功能测试， 它的味道可能不太好，但我们可以一起让它变得更好。



I started the decompressed version of elasticsearch last night, but dmonitor has never been able to establish a connection with elasticsearch. The computer system has always refused dmonitor services to access relevant IP and ports. How do I configure all IP and ports?



I tried the latest dmonitor service several times today. It seems to be running, but I haven't been able to access it http://localhost:5000/ , do I have to install other auxiliary software?



In fact, I want to ask, can you put all the necessary data packets in dmonitor so that I can start with one click without any configuration?



If I choose elasticsearch to start the dmonitor service, what auxiliary software should I install? What configuration files do I want to modify and what specific data do I need to modify?



If I choose DB to start the dmonitor service, what auxiliary software should I install? What configuration files do I want to modify and what specific data do I need to modify?



I think you may have forgotten some important configuration details. I suggest you try to start dmonitor with a pure virtual machine. Maybe all errors can be solved!

![20220729_150231](https://user-images.githubusercontent.com/58470642/181704457-450be56d-3ed6-456c-9902-2706a9aca223.jpg)

**Comment by LRF520** [comment]
> its seens like you have no an es server, and i used an old ElasticSearch client,you intalled a newly es client,some es pameters is not compatibility，i will fix it. i storage the metric data into sqlitedb or es by config, if you have no es, you can change the config/application.yml dmonitor.store to DB. hhh this project is startup and used to resolve some non-functional tests of my last job, its may not taste so good,but we can make it better together.



I try to visit http://localhost:8088/ ,But I think all the data in this interface is abnormal. It's too sad. I don't know where dmonitor will go wrong.I suggest you rebuild it.

![20220729_172758](https://user-images.githubusercontent.com/58470642/181730189-750c1a60-0837-4098-8c24-4aa4263076db.jpg)

**Comment by danielpine** [comment]
Ok bro，let me see see--发自新浪邮箱客户端
在 7月29日 17:32，LRF520 ***@***.***> 写道：




its seens like you have no an es server, and i used an old ElasticSearch client,you intalled a newly es client,some es pameters is not compatibility，i will fix it. i storage the metric data into sqlitedb or es by config, if you have no es, you can change the config/application.yml dmonitor.store to DB. hhh this project is startup and used to resolve some non-functional tests of my last job, its may not taste so good,but we can make it better together.



I try to visit http://localhost:8088/ ,But I think all the data in this interface is abnormal. It's too sad. I don't know where dmonitor will go wrong.I suggest you rebuild it.





&mdash;

**Comment by danielpine** [comment]
![image](https://user-images.githubusercontent.com/33600232/181763435-f33b8871-554a-4a11-a408-76e440e673ba.png)
![image](https://user-images.githubusercontent.com/33600232/181763529-67585191-bc9e-46f1-90e6-36e00c97f3a2.png)

i fix it bro,it works on my mac, you can try it, use DB first,i'll test ES tomorow

**Comment by danielpine** [comment]
btw,you can add my wechat if you wanna.
process filter is also done.
<img width="1727" alt="image" src="https://user-images.githubusercontent.com/33600232/181769976-eb55d62e-62ca-4b2d-9eeb-38d296b76982.png">
