### ISSUE TITLE
Many important functions are not available

### ISSUE THREAD

**Issue by LRF520** [danielpine/dmonitor#3]
Now it is running, but many important functions are not available, so it is difficult to meet basic needs. Dmonitor should become a great tool. It is easy for you to add the following functions, which can help many people:

1. Make all charts refresh automatically, for example, refresh automatically in 3 or 5 seconds;

2. Add real-time network upload speed and real-time network download speed chart;

3. Add real-time utilization chart of hard disk;

4. Add GPU real-time utilization chart;

5. Add the resource usage switch button of the whole system. For example, if we don't open the "whole system" button, dmmonitor will display the resource usage of all processes or a process. If we open the "whole system" button, dmmonitor will display the resource usage of the whole system. I think this kind of data comparison is very necessary to prevent fatal problems, and no one in the world has achieved this functional effect.

![20220802_234143](https://user-images.githubusercontent.com/58470642/182420044-37bf42c6-9a60-499e-be44-b2e544d8e3e2.jpg)

**Comment by danielpine** [comment]
Recently,I'm too busy for my startup company to do more cool and wonderful functions you said,maybe later,and you could develop the functions you want and request a pr.--发自新浪邮箱客户端
在 8月3日 00:02，LRF520 ***@***.***> 写道：

Now it is running, but many important functions are not available, so it is difficult to meet basic needs. Dmonitor should become a great tool. It is easy for you to add the following functions, which can help many people:


Make all charts refresh automatically, for example, refresh automatically in 3 or 5 seconds;


Add real-time network upload speed and real-time network download speed chart;


Add real-time utilization chart of hard disk;


Add GPU real-time utilization chart;


Add the resource usage switch button of the whole system. For example, if we don't open the "whole system" button, dmmonitor will display the resource usage of all processes or a process. If we open the "whole system" button, dmmonitor will display the resource usage of the whole system. I think this kind of data comparison is very necessary to prevent fatal problems, and no one in the world has achieved this functional effect.




&mdash;

**Comment by LRF520** [comment]
> 现在它正在运行，但许多重要功能不可用，因此很难满足基本需求。Dmonitor应该成为一个伟大的工具。您可以轻松添加以下功能，这些功能可以帮助许多人：
> 
> 1. 使所有图表自动刷新，例如，在3或5秒内自动刷新;
> 2. 增加实时网络上传速度和实时网络下载速度图表;
> 3. 增加硬盘实时利用率图表;
> 4. 新增GPU实时利用率图表;
> 5. 添加整个系统的资源使用切换按钮。例如，如果我们不打开“整个系统”按钮，dmmonitor 将显示所有进程或一个进程的资源使用情况。如果我们打开“整个系统”按钮，dmmonitor将显示整个系统的资源使用情况。我认为这种数据比较对于防止致命问题是非常必要的，世界上没有人达到这种功能效果。
> 
> ![20220802_234143](https://user-images.githubusercontent.com/58470642/182420044-37bf42c6-9a60-499e-be44-b2e544d8e3e2.jpg)


Dmonitor is already very good, thank you very much!
