### ISSUE TITLE
Elasticsearch still doesn't work.

### ISSUE THREAD

**Issue by LRF520** [danielpine/dmonitor#4]
Elasticsearch still doesn't work. I think the data performance of elasticsearch is better than that of DB. Repairing elasticsearch is very meaningful.

**Comment by danielpine** [comment]
May some api of elasticsearch-py was desperate.--发自新浪邮箱客户端
在 8月3日 00:07，LRF520 ***@***.***> 写道：

Elasticsearch still doesn't work. I think the data performance of elasticsearch is better than that of DB. Repairing elasticsearch is very meaningful.

&mdash;
